dist: focal
sudo: true
language: python
python:
  - "3.8"

before_install:
  - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh 10
  - ls /usr/bin/llvm*
  - export LLVM_CONFIG=/usr/bin/llvm-config
  - pip install torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
  # - sudo ln -s /usr/bin/llvm-config-10 /usr/bin/llvm-config

install:
  - pip install -r requirements.txt
  - pip uninstall -y shapely
  - pip install --no-binary shapely shapely
  - export PYTHONPATH=src

script:
  - python ./setup.py unittests
