language: python
python:
    - "3.4"
    - "3.5"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran 
install: 
    - pip install -r requirements.txt
    - pip install -U git+https://github.com/quantopian/qgrid --no-deps
    - pip install scipy
    - pip install -r requirements_scikit.txt
    - pip install -r requirements_ext.txt
script:
    - python setup.py unittests
