dist: focal
sudo: true
language: python
python:
  - "3.8"

before_install:
  - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev
  - pip install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

install:
  - pip install -r requirements.txt
  - pip uninstall -y shapely
  - pip install --no-binary shapely shapely
  - export PYTHONPATH=src

script:
  - python ./setup.py unittests
