language: python
python:
    - "3.4"
    - "3.5"
addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy    
install: 
    - pip install -r requirements.txt
    - pip install -r requirements_ext.txt
script:
    - python setup.py unittests
