image:
  - Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  #- "%PYTHON%\\Scripts\\pymy_install3 --set=pyensae"
  #- "%PYTHON%\\Scripts\\pymy_install3 xgboost"
  #- "%PYTHON%\\Scripts\\pymy_install3 h5py"
  #- "%PYTHON%\\Scripts\\pymy_install3 PyYAML x86cpu"
  #- "%PYTHON%\\Scripts\\pymy_install3 pillow psutil protobuf tensorflow torch"
  - "%PYTHON%\\Scripts\\pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html"
  - "%PYTHON%\\Scripts\\pymy_install3 pyproj shapely cartopy"
  - "%PYTHON%\\Scripts\\pymy_install3 opencv_python"
  - "%PYTHON%\\Scripts\\pip install -r requirements_conda.txt"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - set PYTHONPATH=src

build: off

test_script:
  - "%PYTHON%\\python -u setup.py unittests"

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: ensae_projects
