environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 --set=pyensae"
  - "%PYTHON%\\Scripts\\pymy_install3 xgboost"
  - "%PYTHON%\\Scripts\\pymy_install3 h5py"
  - "%PYTHON%\\Scripts\\pymy_install3 PyYAML x86cpu"
  - "%PYTHON%\\Scripts\\pymy_install3 pyproj shapely"
  - "%PYTHON%\\Scripts\\pymy_install3 opencv_python"
  - "%PYTHON%\\Scripts\\pymy_install3 pillow psutil protobuf tensorflow"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - "%PYTHON%\\Scripts\\pip uninstall -y ensae_projects"

build: off

test_script:
  - "%PYTHON%\\python -u setup.py unittests"

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: ensae_projects
