environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 --set=ensae_teaching_cs"
  - "%PYTHON%\\Scripts\\pip install xlrd"
  - "%PYTHON%\\Scripts\\pip install pyquickhelper jyquickhelper"
  - "%PYTHON%\\Scripts\\pip install cryptography beautifulsoup4"
  - "%PYTHON%\\Scripts\\pip install pycryptodome"
  - "%PYTHON%\\Scripts\\pip install pymmails"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pip install pyensae"
  - "%PYTHON%\\Scripts\\pip install pyrsslocal"
  - "%PYTHON%\\Scripts\\pip install mnist"
  - "%PYTHON%\\Scripts\\pymy_install3 xgboost"
  - "%PYTHON%\\Scripts\\pymy_install3 OpenCV"
  - "%PYTHON%\\Scripts\\pymy_install3 PyYAML"
  - "%PYTHON%\\Scripts\\pymy_install3 pyproj"

build: off

test_script:
  - "%PYTHON%\\python -u setup.py unittests"
